apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: worldconfig
  namespace: default
spec:
  accessControl:
    defaultAction: deny 
    trustDomain: public
    policies:
    - appId: greeting-service 
      defaultAction: deny
      trustDomain: public
      namespace: default
      operations:
      - name: /sayWorld
        httpVerb: ['GET'] 
        action: allow
 