apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oauth2clientcreds
  namespace: default
spec:
  type: middleware.http.oauth2clientcredentials
  version: v1
  metadata:
  - name: clientId
    value: "<Client-ID>"
  - name: clientSecret
    value: "<Client-Secret>"
  - name: scopes
    value: "https://graph.microsoft.com/.default"
  - name: tokenURL
    value: "https://login.microsoftonline.com/<Tenant-ID>/oauth2/v2.0/token"
  - name: headerName
    value: "Dapr-Access-Code"
  - name: authStyle
    value: "1"